// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcureRiskAnalyzer.Web.Data;

#nullable disable

namespace ProcureRiskAnalyzer.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250101000000_AddCategoriesTable")]
    partial class AddCategoriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Information Technology Services",
                            Name = "IT Services"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Healthcare and Medical Services",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Infrastructure and Construction",
                            Name = "Infrastructure"
                        });
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Ukraine",
                            Name = "EPAM"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Poland",
                            Name = "SoftServe"
                        });
                });

            modelBuilder.Entity("Tender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Buyer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenderCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Tenders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Buyer = "Міністерство освіти",
                            CategoryId = 1,
                            Date = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpectedValue = 1000000m,
                            SupplierId = 1,
                            TenderCode = "T001"
                        },
                        new
                        {
                            Id = 2,
                            Buyer = "Міністерство охорони здоров'я",
                            CategoryId = 2,
                            Date = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpectedValue = 750000m,
                            SupplierId = 2,
                            TenderCode = "T002"
                        });
                });

            modelBuilder.Entity("Tender", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Tenders")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Tenders");
                });
#pragma warning restore 612, 618
        }
    }
}

